# Generated by Django 4.1.7 on 2023-04-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AuthorOfQuote',
        ),
    ]
