# Generated by Django 4.1.7 on 2023-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_rename_author_authorofquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorofquote',
            name='born_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorofquote',
            name='born_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorofquote',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
