# Generated by Django 4.1.7 on 2023-04-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_authorofquote_born_date_authorofquote_born_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorofquote',
            name='born_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
