# Generated by Django 4.1.7 on 2023-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_alter_authorofquote_born_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorofquote',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
