# Generated by Django 4.1.7 on 2023-04-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_alter_authorofquote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
