# Generated by Django 4.1.7 on 2023-04-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_alter_quote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorofquote',
            name='born_date',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='authorofquote',
            name='born_location',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='authorofquote',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=300),
        ),
    ]
