# Generated by Django 4.1.7 on 2023-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0008_alter_authorofquote_born_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorofquote',
            name='born_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='authorofquote',
            name='born_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='authorofquote',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
